2018-10-16 18:51:42,113 ERROR: Exception on /login [GET] [in c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Cleo\Documents\GitHub\FlaskBlog\app\routes.py", line 51, in login
    return render_template('login.html', title='Entrar', form=form)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Cleo\Documents\GitHub\FlaskBlog\app\templates\base.html", line 21, in template
    <a class="navbar-brand" href="{{ url_for('index') }}">Flaskblog</a>
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\Cleo\Documents\GitHub\FlaskBlog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Cleo\Documents\GitHub\FlaskBlog\app\templates\base.html", line 21, in template
    <a class="navbar-brand" href="{{ url_for('index') }}">Flaskblog</a>
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\parser.py", line 888, in subparse
    self.stream.expect('block_end')
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got 'index'
2018-10-16 18:52:16,367 INFO: Flaskblog startup [in C:\Users\Cleo\Documents\GitHub\FlaskBlog\app\__init__.py:51]
2018-10-16 18:52:20,439 ERROR: Exception on /login [GET] [in c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Cleo\Documents\GitHub\FlaskBlog\app\routes.py", line 51, in login
    return render_template('login.html', title='Entrar', form=form)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Cleo\Documents\GitHub\FlaskBlog\app\templates\base.html", line 21, in template
    <a class="navbar-brand" href="{{ url_for('index') }}">Flaskblog</a>
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\Cleo\Documents\GitHub\FlaskBlog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Cleo\Documents\GitHub\FlaskBlog\app\templates\base.html", line 21, in template
    <a class="navbar-brand" href="{{ url_for('index') }}">Flaskblog</a>
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\parser.py", line 888, in subparse
    self.stream.expect('block_end')
  File "c:\users\cleo\documents\github\flaskblog\venv\lib\site-packages\jinja2\lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got 'index'
2018-10-16 18:52:43,625 INFO: Flaskblog startup [in C:\Users\Cleo\Documents\GitHub\FlaskBlog\app\__init__.py:51]
